#!/usr/bin/env python
"""
Git commit hook:
./hooks/commit-msg
Check commit message according to guidelines
"""

import sys
import re

REGEX = '^(JR|jr)\: [A-Z]-[0-9]+; .'

e.g. ^(feat|fix|docs|style|refactor|test|build|ci|perf)((.+))?\:\s(.{3,})
GUIDELINE_LINK = '<link to relvent commit mesage guideline>'

e.g. https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
with open(sys.argv[1]) as commit:
lines = commit.readlines()
if len(lines) == 0:
sys.stderr.write("\n[ERROR]: Empty commit message\n")
sys.stderr.write("\n - Refer commit guide: {}\n\n".format(help_address))
sys.exit(1)

match_regex = re.match('({})'.format(REGEX), lines[0])

if match_regex is None:
sys.stderr.write("\n[ERROR]: Your commit message subject line does not follow the guideline\n")
sys.stderr.write("\n - Refer commit guideline: {}\n\n".format(GUIDELINE_LINK))
sys.exit(1)

sys.stderr.write("\n[INFO]: Your commit message looks good! \n\n")
sys.exit(0)
